import BottomBar from "@/components/BottomBar";
import Header from "@/components/Header";
import MenuIcon from "@/components/MenuIcon";
import AuthProvider from "@/provider/AuthProvider";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  paralel,
}: Readonly<{
  children: React.ReactNode;
  paralel: React.ReactNode;
}>) {
  return (
    <>
      <Suspense>
        <AuthProvider>
          <Header />
          <main className="w-full mx-auto max-w-md  bg-white pb-8">
            {children}
            {paralel}
            <BottomBar />
          </main>
        </AuthProvider>
      </Suspense>
    </>
  );
}
